# Generated by Django 5.2.5 on 2025-08-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(help_text="Small heading, e.g., 'Welcome To'", max_length=100)),
                ('title_large', models.CharField(help_text="Main heading, e.g., 'Milkar Seva Sansthan'", max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Main slider image', upload_to='sliders/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sliders/logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Set True to show this slide')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
