# Generated by Django 5.2.5 on 2025-08-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Image caption or title', max_length=200, null=True)),
                ('image', models.ImageField(help_text='Upload gallery image', upload_to='gallery/')),
                ('is_active', models.BooleanField(default=True, help_text='Show/Hide this image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
