# Generated by Django 5.2.5 on 2025-08-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_aboutus_aboutusitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us ', 'verbose_name_plural': 'About Us '},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='button_link',
        ),
    ]
