# Generated by Django 5.2.5 on 2025-08-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_aboutus_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='section_type',
            field=models.CharField(choices=[('about', 'About Us'), ('core_values', 'Core Values'), ('our_work', 'Our Work'), ('impact', 'Our Impact'), ('join_us', 'Join Us'), ('contribute', 'How You Can Contribute'), ('why_join', 'Why Join Us')], max_length=50, unique=True),
        ),
    ]
