# Generated by Django 5.2.5 on 2025-08-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_aboutus_is_deleted_bankdetails_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the user', max_length=150)),
                ('email', models.EmailField(help_text='Email address of the user', max_length=200)),
                ('mobile', models.CharField(help_text='Mobile number of the user', max_length=15)),
                ('message', models.TextField(help_text='Message content from user')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the message was submitted')),
                ('is_read', models.BooleanField(default=False, help_text='Mark True when admin reads the message')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
