# Generated by Django 5.2.5 on 2025-08-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
