# Generated by Django 5.2.5 on 2025-09-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_users_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Image caption or title', max_length=200, null=True)),
                ('image', models.ImageField(help_text='Upload certificate image', upload_to='certificate/')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show/Hide this image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
