# Generated by Django 5.2.5 on 2025-09-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('years', models.PositiveIntegerField()),
                ('icon_class', models.CharField(blank=True, default='fa-solid fa-trophy', max_length=100, null=True)),
                ('badge_class', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show/Hide this image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-years'],
            },
        ),
    ]
