# Generated by Django 5.2.5 on 2025-09-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='badge_class',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='icon_class',
        ),
    ]
