# Generated by Django 5.2.5 on 2025-09-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_remove_awards_badge_class_remove_awards_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='award_image',
            field=models.ImageField(blank=True, null=True, upload_to='awards/'),
        ),
    ]
