# Generated by Django 5.2.5 on 2025-09-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_awards_award_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='award_image',
            field=models.ImageField(default=1, upload_to='awards/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='awards',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='awards',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
