# Generated by Django 5.2.5 on 2025-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_alter_awards_award_image_alter_awards_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('sponsor', 'Sponsor')], max_length=50)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(default='fas fa-user-friends', max_length=100)),
                ('icon_color', models.CharField(default='text-danger', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ourteam/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
