# Generated by Django 5.2.5 on 2025-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_ourteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
