# Generated by Django 5.2.5 on 2025-09-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_ourteam_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteam',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='ourteam',
            name='icon_color',
        ),
    ]
