# Generated by Django 5.2.5 on 2025-09-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_remove_ourteam_icon_remove_ourteam_icon_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteam',
            name='photo',
        ),
    ]
