# Generated by Django 5.2.5 on 2025-09-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_remove_ourteam_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='ourteam/'),
        ),
    ]
