# Generated by Django 5.2.5 on 2025-09-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_remove_ourteam_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=150, null=True)),
                ('icon', models.CharField(default='fas fa-user-friends', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
