# Generated by Django 5.2.5 on 2025-09-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_managementmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='icon',
            field=models.CharField(default='fas fa-user-friends', max_length=50),
        ),
    ]
