# Generated by Django 5.2.5 on 2025-09-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_ourteam_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementmember',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='ourteam',
            name='icon',
        ),
    ]
