# Generated by Django 5.2.5 on 2025-09-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_remove_managementmember_icon_remove_ourteam_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
