# Generated by Django 5.2.5 on 2025-09-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_missionvision'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionvision',
            name='icon',
            field=models.CharField(default=1, help_text='FontAwesome class e.g. fas fa-book-reader', max_length=50),
            preserve_default=False,
        ),
    ]
