# Generated by Django 5.2.5 on 2025-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_missionvision_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=150)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('date', models.DateField()),
                ('received_from', models.CharField(blank=True, max_length=150, null=True)),
                ('rupees_in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('test', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(max_length=50)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
