# Generated by Django 5.2.5 on 2025-09-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='receipt_number',
        ),
    ]
