# Generated by Django 5.2.5 on 2025-09-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_remove_donation_receipt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='received_from',
        ),
    ]
