# Generated by Django 5.2.5 on 2025-09-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0028_remove_donation_received_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='message',
        ),
    ]
