# Generated by Django 5.2.5 on 2025-09-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0029_remove_donation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='rupees_in_words',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='test',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='transaction_id',
        ),
    ]
