# Generated by Django 5.2.5 on 2025-09-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0030_remove_donation_address_remove_donation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='image',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='section_type',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='button_text',
            field=models.CharField(default='Know more About Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AboutUsItem',
        ),
    ]
