# Generated by Django 5.2.5 on 2025-09-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0031_alter_aboutus_options_rename_image_aboutus_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show/Hide this image'),
        ),
    ]
