# Generated by Django 5.2.5 on 2025-09-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0033_corevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('paragraph', models.CharField(max_length=350)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
