# Generated by Django 5.2.5 on 2025-09-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0034_ourwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourwork',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='ourwork',
            name='paragraph',
        ),
    ]
