# Generated by Django 5.2.5 on 2025-09-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0035_remove_ourwork_heading_remove_ourwork_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
