# Generated by Django 5.2.5 on 2025-09-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0036_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='corevalue',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show/Hide this image'),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
