# Generated by Django 5.2.5 on 2025-09-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0037_corevalue_is_active_corevalue_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoreValue',
        ),
        migrations.DeleteModel(
            name='Impact',
        ),
        migrations.DeleteModel(
            name='OurWork',
        ),
    ]
