# Generated by Django 5.2.5 on 2025-09-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0038_delete_corevalue_delete_impact_delete_ourwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
