# Generated by Django 5.2.5 on 2025-09-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0039_slider_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='logo',
            field=models.ImageField(default=1, upload_to='sliders/logos/'),
            preserve_default=False,
        ),
    ]
