# Generated by Django 5.2.5 on 2025-09-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0040_alter_slider_description_alter_slider_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default=1, help_text='Image caption or title', max_length=200),
            preserve_default=False,
        ),
    ]
