# Generated by Django 5.2.5 on 2025-09-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0041_alter_gallery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='button_text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(default=1, help_text='Image caption or title', max_length=200),
            preserve_default=False,
        ),
    ]
