# Generated by Django 5.2.5 on 2025-09-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0042_alter_certificate_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='organization',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
