# Generated by Django 5.2.5 on 2025-09-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0043_alter_ourteam_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementmember',
            name='organization',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
