# Generated by Django 5.2.5 on 2025-09-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0044_alter_managementmember_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='logo',
            field=models.ImageField(default=1, upload_to='about/'),
            preserve_default=False,
        ),
    ]
