# Generated by Django 5.2.5 on 2025-09-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0045_alter_aboutus_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
