# Generated by Django 5.2.5 on 2025-08-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(blank=True, default='59a5cbc4', max_length=8, unique=True),
        ),
    ]
