# Generated by Django 5.2.5 on 2025-08-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alter_admin_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(blank=True, default='1190a874', max_length=8, unique=True),
        ),
    ]
