# Generated by Django 5.2.5 on 2025-09-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0038_alter_admin_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(blank=True, default='2a649158', max_length=8, unique=True),
        ),
    ]
