# Generated by Django 5.2.5 on 2025-09-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0056_alter_admin_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(blank=True, default='c2b5e9bf', max_length=8, unique=True),
        ),
    ]
