# Generated by Django 5.2.5 on 2025-09-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0061_alter_admin_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(blank=True, default='07d04ad8', max_length=8, unique=True),
        ),
    ]
