# Generated by Django 5.2.5 on 2025-09-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0062_admin_profile_image_alter_admin_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(blank=True, default='4f125035', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_password',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
