# Generated by Django 5.2.5 on 2025-09-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0063_alter_admin_admin_id_alter_admin_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(blank=True, default='5cf250a5', max_length=8, unique=True),
        ),
    ]
